### ISSUE TITLE
crash on daemon start

### ISSUE THREAD

**Issue by autonome** [codynhat/ipfs-ios-backup#6]
Mac OS X 10.14.6 (18G5033)

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe0 pc=0x4476a49]

goroutine 1 [running]:
github.com/spf13/viper.(*Viper).AllKeys(0x0, 0x4f9a720, 0x5f7fda0, 0xc0005245a0)
        /private/tmp/ipfs-ios-backup-20200527-63450-y5i45w/ipfs-ios-backup-0.2.0/pkg/mod/github.com/spf13/viper@v1.4.0/viper.go:1673 +0x99
github.com/spf13/viper.(*Viper).AllSettings(0x0, 0xc0001dfaa0)
        /private/tmp/ipfs-ios-backup-20200527-63450-y5i45w/ipfs-ios-backup-0.2.0/pkg/mod/github.com/spf13/viper@v1.4.0/viper.go:1753 +0x51
github.com/codynhat/ipfs-ios-backup/cmd.startSchedules(0x5422e00, 0xc0004ec480, 0x0, 0xc000313820, 0x20, 0xc00024e3c0, 0x0)
        /private/tmp/ipfs-ios-backup-20200527-63450-y5i45w/ipfs-ios-backup-0.2.0/src/github.com/codynhat/ipfs-ios-backup/cmd/daemon.go:150 +0xdf
github.com/codynhat/ipfs-ios-backup/cmd.glob..func5(0x5f2d2c0, 0x5f7e8e0, 0x0, 0x0)
        /private/tmp/ipfs-ios-backup-20200527-63450-y5i45w/ipfs-ios-backup-0.2.0/src/github.com/codynhat/ipfs-ios-backup/cmd/daemon.go:68 +0x25c
github.com/spf13/cobra.(*Command).execute(0x5f2d2c0, 0x5f7e8e0, 0x0, 0x0, 0x5f2d2c0, 0x5f7e8e0)
        /private/tmp/ipfs-ios-backup-20200527-63450-y5i45w/ipfs-ios-backup-0.2.0/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:842 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x5f2d800, 0x5f2d560, 0xc00045ff48, 0x40458ca)
        /private/tmp/ipfs-ios-backup-20200527-63450-y5i45w/ipfs-ios-backup-0.2.0/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
        /private/tmp/ipfs-ios-backup-20200527-63450-y5i45w/ipfs-ios-backup-0.2.0/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
github.com/codynhat/ipfs-ios-backup/cmd.Execute()
        /private/tmp/ipfs-ios-backup-20200527-63450-y5i45w/ipfs-ios-backup-0.2.0/src/github.com/codynhat/ipfs-ios-backup/cmd/root.go:91 +0x31
main.main()
        /private/tmp/ipfs-ios-backup-20200527-63450-y5i45w/ipfs-ios-backup-0.2.0/src/github.com/codynhat/ipfs-ios-backup/main.go:27 +0x20

**Comment by autonome** [comment]
@codynhat any ideas?

**Comment by codynhat** [comment]
It looks like there is an issue with the configuration field `schedules`. I believe this is fixed in `0.3.x`. Can you try upgrading?

Thanks for all the feedback @autonome!
